export const URL_GITHUB = "https://github.com/igor-p/"
export const URL_LINKEDIN = "https://www.linkedin.com/in/igor-pok/"
export const URL_X = "https://x.com/YoungKesef"
export const URL_TELEGRAM = "https://t.me/youngkesef"
export const EMAIL = "mailto:ipokrysh@gmail.com"
